---
-
  become: true
  handlers:
    -
      name: "restart nginx"
      service: "name=nginx state=restarted"
  hosts: all
  name: "install nginx"
  tasks:
    -
      apt:
        name: nginx
        state: present
      name: "ensure webserver package is present"
    -
      name: Templating
      notify:
        - "restart nginx"
      template: "src={{ source_folder }}/index.j2 dest={{ dest_folder}}/index.html mode=0555"
  vars:
    dest_folder: /var/www/html
    source_folder: ./
