---
- name: webserver configurations
  hosts: web
  become: yes

  roles:
    - common
    - webserver
    - security

- name: db configuration
  hosts: db
  become: yes

  roles:
    - common
    - security