---
# tasks file for webserver
- name: unsure webserver packages is present
  apt:
    name: nginx
    state: present

- name: ensure index.html is present
  copy: src=index.html dest={{ dest_folder }}/index.html mode=0555
  notify:
    - restart nginx
